repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    # -   id: end-of-file-fixer
    # -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=10240', --enforce-all]
    -   id: check-json
    -   id: check-yaml

default_stages: [commit, push]