deployment_server_names:
  - name: common_deployment_template
    replicas: 2
    label: large
    taint: blue
    image: nginx
    file:
    - "nginx-deployment-1"
    - "nginx-deployment-2"

  - name: common_deployment_template
    replicas: 1
    label: small
    taint: green
    image: alpine
    file:
    - "alpine-deployment-1"

  - name: common_deployment_template
    replicas: 1
    label: medium
    taint: blue
    image: redis
    file:
    - "redis-deployment-1"
