apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: centos-job
  generateName: uat2-centos-job-1-
  namespace: uat2
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: centos-job
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "size"
                operator: In
                values:
                - medium
      containers:
      - image: centos
        imagePullPolicy: IfNotPresent
        name: centos-job
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["sleep", "10"]
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      tolerations:
      - effect: NoSchedule
        key: "spray"
        operator: "Equal"
        value: blue