---
- name: converting jinja to deployment/job yaml
  template:
    src: "../jinja/common_{{ type }}_template.j2"
    dest: "../templates/{{ namespace }}/{{ namespace }}-cop-{{ item.1 }}.yaml"
  register: file_status
  ignore_errors: true
  tags: always

- name: checking file status
  debug:
    msg: "{{ item.1 }} did not get converted properly"
  when: file_status.failed == true
  tags: always

- name: Run k8s deployment
  shell: yamllint -c ../validate_yaml_config/validate.yaml "../templates/"
  when: file_status.failed == false
  tags: always

- name: Run k8s deployment
  shell: kubectl create -f ../templates/{{ namespace }}/{{ namespace }}-cop-{{ item.1 }}.yaml
  when: file_status.failed == false
  tags: always
