---
- name: check if folders exist
  stat:
    path: "../templates/{{ namespace }}"
  register: dir_status
  tags: always

- name: create directory if not existing
  file:
    path: "../templates/{{ namespace }}"
    state: directory
    mode: "0755"
  when: not dir_status.stat.exists
  tags: always

- name: Running sub tasks for deployment
  include_tasks: convert.yaml
  loop: "{{ deployment_server_names | subelements('file', 'skip_missing=true') }}"
  tags:
    - create-deployment

- name: Running sub tasks for job
  include_tasks: convert.yaml
  loop: "{{ job_server_names | subelements('file', 'skip_missing=true') }}"
  tags:
    - create-job