apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-07-31T05:28:05Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: my-cluster-worker4
    kubernetes.io/os: linux
    size: medium
  name: my-cluster-worker4
  resourceVersion: "30782"
  selfLink: /api/v1/nodes/my-cluster-worker4
  uid: 2927ad1e-3681-445d-ab3f-2facb14594d0
spec:
  podCIDR: 10.244.2.0/24
  podCIDRs:
  - 10.244.2.0/24
  providerID: kind://docker/my-cluster/my-cluster-worker4
  taints:
  - effect: NoSchedule
    key: spray
    value: blue
status:
  addresses:
  - address: 172.18.0.3
    type: InternalIP
  - address: my-cluster-worker4
    type: Hostname
  allocatable:
    cpu: "20"
    ephemeral-storage: 263174212Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8061872Ki
    pods: "110"
  capacity:
    cpu: "20"
    ephemeral-storage: 263174212Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8061872Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2022-07-31T07:56:06Z"
    lastTransitionTime: "2022-07-31T05:28:05Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-07-31T07:56:06Z"
    lastTransitionTime: "2022-07-31T05:28:05Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-07-31T07:56:06Z"
    lastTransitionTime: "2022-07-31T05:28:05Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-07-31T07:56:06Z"
    lastTransitionTime: "2022-07-31T05:28:35Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - k8s.gcr.io/etcd:3.4.13-0
    sizeBytes: 254659261
  - names:
    - k8s.gcr.io/kube-proxy:v1.19.1
    sizeBytes: 135907926
  - names:
    - docker.io/kindest/kindnetd:v20200725-4d6bea59
    sizeBytes: 118720874
  - names:
    - k8s.gcr.io/kube-apiserver:v1.19.1
    sizeBytes: 95011120
  - names:
    - k8s.gcr.io/kube-controller-manager:v1.19.1
    sizeBytes: 84149058
  - names:
    - k8s.gcr.io/kube-scheduler:v1.19.1
    sizeBytes: 65056560
  - names:
    - k8s.gcr.io/build-image/debian-base:v2.1.0
    sizeBytes: 53876619
  - names:
    - k8s.gcr.io/coredns:1.7.0
    sizeBytes: 45355487
  - names:
    - docker.io/library/redis@sha256:ed8cba11c09451dbb3495f15951e4afb4f1ba72a4a13e135c6da06c6346e0333
    - docker.io/library/redis:latest
    sizeBytes: 42350094
  - names:
    - docker.io/rancher/local-path-provisioner:v0.0.14
    sizeBytes: 41982521
  - names:
    - k8s.gcr.io/pause:3.3
    sizeBytes: 685708
  nodeInfo:
    architecture: amd64
    bootID: 1a65377e-b3c2-4d1c-82ce-08586eb1787c
    containerRuntimeVersion: containerd://1.4.0
    kernelVersion: 5.10.16.3-microsoft-standard-WSL2
    kubeProxyVersion: v1.19.1
    kubeletVersion: v1.19.1
    machineID: de2bf6730005402e93d8e889b09f1fb2
    operatingSystem: linux
    osImage: Ubuntu Groovy Gorilla (development branch)
    systemUUID: de2bf6730005402e93d8e889b09f1fb2
