name: Perform Quality check on the repo

on:
  push:
    branches: [ develop ]
    path: [ '**.yaml', '**.yml' ]
  pull_request:
    type: [ opened, edited, reopened, synchronize ]
    branches: [ main ]

jobs:
  quality_checks:
    name: Perform quality check
    runs-on: [self-hosted, label-1]
    steps:
    - uses: actions/checkout@v2
    - name: check python version
      run: pip -V
    - name: install pre-commit plugin
      run: pip install pre-commit
    - run: pre-commit install
    - name: run pre-commit checks on files
      run: pre-commit run --all-files --show-diff-on-failure
      