name: Perform Quality check on the repo

on:
  push:
    branches: [ main, Quality_check_action ]
    path: [ '**.yaml', '**.yml' ]
  pull_request:
    type: [ opened, edited, reopened, synchronize ]
    branches: [ main ]

jobs:
  quality_checks:
    name: Perform quality check
    runs-on: [self-hosted, label-1]
    steps:
    - uses: actions/checkout@v2
    - name: check python version
      run: pip -V
    - name: install pre-commit plugin
      run: pip install pre-commit
    - run: pre-commit install
    - name: run pre-commit checks on files
      run: pre-commit run --all-files --show-diff-on-failure
  provision_cluster:
    name: Provision K8s cluster via Ansible
    runs-on: [self-hosted, label-1]
    needs: quality_checks
    steps:
    - uses: actions/checkout@v2
    - name: Run ansible playbook to provision cluster
      run: ansible-playbook -e "namespace=sit2 type=deployment" ansible-practice/playbooks/deploy-kind-cluster.yaml --tags "create-deployment"